### ISSUE TITLE
truffle debugger not working with singletons

### ISSUE THREAD

**Issue by skyeatshorizon** [OpenZeppelin/openzeppelin-test-helpers#150] opened 2021-01-13 15:02 UTC
Hi Im not able to debug a transaction if  `await singletons.ERC1820Registry(accounts[0]);` was used before.
Im always getting this error:
```
Starting Truffle Debugger...
✖ Gathering information about your project and the transaction...
ProviderError: CONNECTION ERROR: Couldn't connect to node on WS.
    at /home/user/project/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:73:1
    at /home/user/project/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:102:1
    at Object.callback (/home/user/project/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1)
    at /home/user/project/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:188:1
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/user/project/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:187:1)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/user/project/node_modules/truffle/build/webpack:/node_modules/yaeti/lib/EventTarget.js:115:1)
    at W3CWebSocket.onClose (/home/user/project/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:228:1)
    at WebSocketConnection.<anonymous> (/home/user/project/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:201:1)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:467:12)
    at WebSocketConnection.drop (/home/user/project/node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:475:1)
    at WebSocketConnection.processFrame (/home/user/project/node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:578:1)
    at /home/user/project/node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:323:34
```
After deleting `await singletons.ERC1820Registry(accounts[0]);` the debugger works as usual.
I hope you can help me.

**Comment by frangio** [comment] 2021-01-13 23:21
Hi @skyeatshorizon. Thank you for reporting this. I am not familiar with Truffle Debugger but I will ask for help and get back to you.

**Comment by frangio** [comment] 2021-01-13 23:55
@skyeatshorizon Can you provide more detailed steps so that we can reproduce the issue? What does your code look like and what command are you running exactly. Thank you.

**Comment by skyeatshorizon** [comment] 2021-01-14 09:48
@frangio Thx for your answer. 'Im using the latest version of test-helpers
```
Truffle v5.1.60 (core: 5.1.60)
Solidity - 0.6.9 (solc-js)
Node v14.15.3
Web3.js v1.2.9
```
I'm using a contract("Base") which is linked to a library. This library can deploy new ERC-777 token instances on demand.
The first Thing I do is migrating my contracts to the chain along with the ERC1820Registry. The next thing I do is calling the Base contract to create a new erc-777 Instance using the library. After this transaction goes through I want to use the debugger which does not work.

**Comment by abcoathup** [comment] 2021-01-15 06:30
Hi @skyeatshorizon,

I am not familiar with the Truffle Debugger.  
I wasn't able to reproduce the issue, but this may be because I don't have the debugger configured correctly.

Testing using `ganache-cli`
```
$ npx truffle version
Truffle v5.1.62 (core: 5.1.62)
Solidity - 0.6.12 (solc-js)
Node v14.9.0
Web3.js v1.2.9
```

```
$ npx truffle test --debug

Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Simple777Token.sol
> Compiling @openzeppelin/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts/introspection/IERC1820Registry.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/token/ERC777/ERC777.sol
> Compiling @openzeppelin/contracts/token/ERC777/IERC777.sol
> Compiling @openzeppelin/contracts/token/ERC777/IERC777Recipient.sol
> Compiling @openzeppelin/contracts/token/ERC777/IERC777Sender.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Artifacts written to /tmp/test--15631-4RHHPE6vDVRs
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Emscripten.clang



  Contract: Simple777Token

  ...
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  Test run interrupted.
  Debugging Simple777Token.new()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Starting Truffle Debugger...
✔ Gathering information about your project...

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(c) continue until breakpoint
(;) step instruction (include number to step multiple)
(g) turn on generated sources, (G) turn off generated sources except via `;`
(p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
(l) print additional source context, (s) print stacktrace, (h) print this help
(q) quit, (r) reset, (t) load new transaction, (T) unload transaction
(b) add breakpoint (`b [[<source-file>:]<line-number>]`; see docs for more)
(B) remove breakpoint (similar to adding, or `B all` to remove all)
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values, (:) evaluate expression - see `v`

debug(development)>
```

## Simple777Token.sol
```solidity
// contracts/Simple777Token.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.2;

import "@openzeppelin/contracts/token/ERC777/ERC777.sol";

/**
 * @title Simple777Token
 * @dev Very simple ERC777 Token example, where all tokens are pre-assigned to the creator.
 * Note they can later distribute these tokens as they wish using `transfer` and other
 * `ERC20` or `ERC777` functions.
 * Based on https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.5.1/contracts/examples/SimpleToken.sol
 */
contract Simple777Token is ERC777 {
    /**
     * @dev Constructor that gives msg.sender all of existing tokens.
     */
    constructor() public ERC777("Simple777Token", "S7", new address[](0)) {
        _mint(msg.sender, 10000 * 10**18, "", "");
    }
}
```
## Simple777Token.test.js
```js
// test/Simple777Token.test.js
// Based on https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.5.1/test/examples/SimpleToken.test.js
const { expect } = require('chai');

const { expectEvent, singletons, constants, BN } = require('@openzeppelin/test-helpers');
const { ZERO_ADDRESS } = constants;

const Simple777Token = artifacts.require('Simple777Token');

contract('Simple777Token', function ([_, registryFunder, creator, operator]) {
  beforeEach(async function () {
    this.erc1820 = await singletons.ERC1820Registry(registryFunder);
    this.token = await debug(Simple777Token.new({ from: creator }));
  });

  it('has a name', async function () {
    expect(await this.token.name()).to.be.equal('Simple777Token');
  });
});
```

**Comment by skyeatshorizon** [comment] 2021-01-15 10:06
@abcoathup Thank you for your answer. 
We cannot share our src code. However, I will open a new repo and build a minimal example. I'll invite you afterwards if it's ok

**Comment by skyeatshorizon** [comment] 2021-01-15 17:49
After some extensive testing I think this is more a problem related to the truffle debugger. I'll post my issue in their github and get back to you once I have more results.
Thx

**Comment by frangio** [comment] 2021-01-15 20:39
I'll close this but feel free to reach out again!

**Closed by frangio** 2021-01-15 20:39 UTC
